app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile_show:
    path: /profile
    defaults: { _controller: AppBundle:Profile:show }
    
